debug:
  local_log: false
  reset_on_load: false
  log_file: "logs/spotted.log"
  log_error_file: "logs/spotted_error.log"
  db_file: "spotted.sqlite3"
  backup_chat_id: 0
  crypto_key: ""
  zip_backup: false
post:
  community_group_id: -1
  channel_id: -2
  channel_tag: "@channel_tag"
  comments: true
  admin_group_id: -3
  n_votes: 2
  remove_after_h: 12
  report: true
  report_wait_mins: 30
  replace_anonymous_comments: true
  delete_anonymous_comments: true
  reject_after_autoreply: true
  autoreplies_per_page: 6
  blacklist_messages: []
  max_n_warns: 3
  warn_expiration_days: 60
  mute_default_duration_days: 7
token: ""
bot_tag: "@bot_tag"
